### ISSUE TITLE
Visualize data from reports

### ISSUE THREAD

**Issue by mgutierrezz** [Marcoror150/CHP-Capping#7]
possibly use D3 Javascript

**Comment by Marcoror150** [comment]
Waiting for example spreadsheets to continue on this issue.

**Comment by Marcoror150** [comment]
Whoops

**Comment by Marcoror150** [comment]
Visualizing data is now successful. Just need to implement saving the charts for future use.

**Comment by Marcoror150** [comment]
Charts can now be saved for future use.
